from django.db import models


class Status(models.IntegerChoices):
    NOT_RUN = 1, "NOT_RUN"
    IN_PROGRESS = 2, "IN_PROGRESS"
    FAILED = 3, "FAILED"
    COMPLETED = 4, "COMPLETED"
    WAITING_APPROVAL = 5, "WAITING_APPROVAL"
    REJECTED = 6, "REJECTED"
    WAITING = 7, "WAITING"
    COMPLETED_WITH_WARNINGS = 8, "COMPLETED_WITH_WARNINGS"
    OUTDATED = 10, "OUTDATED"
    SUBMITTED = 11, "SUBMITTED"


RETRY_CONTINUE_STATUSES = [
    Status.FAILED,
    Status.COMPLETED_WITH_WARNINGS,
]
COMPLETED_STATUSES = [Status.COMPLETED, Status.COMPLETED_WITH_WARNINGS]


class ArchiveState(models.IntegerChoices):
    NONE = 1, "NONE"
    SIP = 2, "SIP"
    AIP = 3, "AIP"


class StepName(models.TextChoices):
    FILE_UPLOAD = "FILE_UPLOAD"
    SIP_UPLOAD = "SIP_UPLOAD"
    HARVEST = "HARVEST"
    VALIDATION = "VALIDATION"
    ARCHIVE = "ARCHIVE"
    EDIT_MANIFEST = "EDIT_MANIFEST"
    INVENIO_RDM_PUSH = "INVENIO_RDM_PUSH"
    ANNOUNCE = "ANNOUNCE"
    PUSH_TO_CTA = "PUSH_TO_CTA"
    EXTRACT_TITLE = "EXTRACT_TITLE"
    NOTIFY_SOURCE = "NOTIFY_SOURCE"


class FilterType(models.TextChoices):
    CREATED = "created"
    UPDATED = "updated"


class BatchStatus(models.TextChoices):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    PARTIALLY_FAILED = "PARTIALLY_FAILED"
    FAILED = "FAILED"


class StepFailureType(models.TextChoices):
    TIMEOUT = "TIMEOUT"
    CONNECTION_ERROR = "CONNECTION_ERROR"
    FILE_ALREADY_EXISTS = "FILE_ALREADY_EXISTS"
    MISSING_INPUT_DATA = "MISSING_INPUT_DATA"
    MISSING_OUTPUT_DATA = "MISSING_OUTPUT_DATA"
    USER_INPUT_REQUIRED = "USER_INPUT_REQUIRED"
    SIZE_EXCEEDED = "SIZE_EXCEEDED"
    AGGR_SIZE_EXCEEDED = "AGGR_SIZE_EXCEEDED"
    PACKAGE_NOT_FOUND = "PACKAGE_NOT_FOUND"
    PATH_NOT_FOUND = "PATH_NOT_FOUND"
    INVALID_SCHEMA = "INVALID_SCHEMA"
    CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
    STEP_DISABLED = "STEP_DISABLED"
    STORAGE_FULL = "STORAGE_FULL"
    HTTP_400 = "HTTP_400"
    HTTP_401 = "HTTP_401"
    HTTP_403 = "HTTP_403"
    HTTP_404 = "HTTP_404"
    HTTP_429 = "HTTP_429"
    HTTP_500 = "HTTP_500"
    HTTP_502 = "HTTP_502"
    HTTP_REDIRECT = "HTTP_REDIRECT"
    HTTP_OTHER = "HTTP_OTHER"
    OTHER = "OTHER"
