# Generated by Django 3.2.4 on 2022-06-21 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_url', models.CharField(max_length=100)),
                ('recid', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('path_to_sip', models.CharField(max_length=100)),
                ('next_steps', models.JSONField(default=list, max_length=50)),
                ('manifest', models.JSONField(default=None, null=True)),
                ('staged', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('restricted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'permissions': (('grant_view_right', 'Grant view right'),),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('indico_api_key', models.TextField(blank=True, max_length=500)),
                ('codimd_api_key', models.TextField(blank=True, max_length=500)),
                ('sso_comp_token', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(choices=[(1, 'Sip Upload'), (2, 'Harvest'), (3, 'Validation'), (4, 'Checksum'), (5, 'Archive'), (6, 'Edit Manifest')])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=None, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Not Run'), (2, 'In Progress'), (3, 'Failed'), (4, 'Completed'), (5, 'Waiting Approval'), (6, 'Rejected'), (7, 'Waiting')], default=1)),
                ('celery_task_id', models.CharField(default=None, max_length=50, null=True)),
                ('input_data', models.TextField(default=None, null=True)),
                ('output_data', models.TextField(default=None, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='oais.archive')),
                ('input_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step', to='oais.step')),
            ],
            options={
                'permissions': [('can_access_all_archives', 'Can access all the archival requests'), ('can_approve_archive', 'Can approve an archival request'), ('can_reject_archive', 'Can reject an archival request')],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=50, null=True)),
                ('description', models.TextField(default=None, max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('internal', models.BooleanField(default=False)),
                ('archives', models.ManyToManyField(blank=True, related_name='archive_collections', to='oais.Archive')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='last_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_step', to='oais.step'),
        ),
    ]
