# Generated by Django 3.2.4 on 2021-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('recid', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
