# Generated by Django 3.2.4 on 2022-04-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('oais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('indico_api_key', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-id'], 'permissions': (('grant_view_right', 'Grant view right'),)},
        ),
        migrations.AddField(
            model_name='archive',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archive',
            name='staged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archive',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collection',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Run'), (2, 'In Progress'), (3, 'Failed'), (4, 'Completed'), (5, 'Waiting Approval'), (6, 'Rejected'), (7, 'Waiting')], default=1),
        ),
    ]
