# Generated by Django 3.2.4 on 2022-07-28 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oais', '0002_auto_20220721_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('recid', models.CharField(max_length=50)),
                ('invenio_id', models.CharField(max_length=50)),
                ('invenio_parent_id', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('invenio_parent_url', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='archive',
            name='invenio_parent_id',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='invenio_parent_url',
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tmp_dir', models.CharField(max_length=100)),
                ('sip_dir', models.CharField(max_length=100)),
                ('files', models.JSONField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploadjobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oais.resource'),
        ),
    ]
