# Generated by Django 3.2.4 on 2022-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0004_auto_20220729_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claims',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
