# Generated by Django 3.2.4 on 2022-12-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0006_auto_20221123_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='restricted',
            field=models.BooleanField(default=True),
        ),
    ]
