# Generated by Django 3.2.4 on 2022-12-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0007_alter_archive_restricted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-id'], 'permissions': (('grant_view_right', 'Grant view right'), ('can_unstage', 'Can unstage a record and start the pipeline'))},
        ),
    ]
