# Generated by Django 3.2.4 on 2023-01-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0008_alter_archive_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.IntegerField(choices=[(1, 'Sip Upload'), (2, 'Harvest'), (3, 'Validation'), (4, 'Checksum'), (5, 'Archive'), (6, 'Edit Manifest'), (7, 'Invenio Rdm Push'), (8, 'Announce')]),
        ),
    ]
