# Generated by Django 4.2.1 on 2023-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0010_alter_step_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
