# Generated by Django 4.2.1 on 2023-12-13 14:44

from django.db import migrations, models
from oais_platform.oais.models import ArchiveState, Status, Steps
import django.db.models.deletion


def save_archives(apps, schema_editor):
    archives = apps.get_model("oais", "Archive")
    steps = apps.get_model("oais", "Step").objects.all()

    for obj in archives.objects.all():
        obj.last_completed_step = obj.last_step
        try:
            archive_steps = steps.filter(archive_id=obj.id).order_by("-start_date")
            obj.last_modification_timestamp = obj.timestamp
            if len(archive_steps) > 0:
                obj.last_step = archive_steps[0]
                if archive_steps[0].finish_date:
                    obj.last_modification_timestamp = archive_steps[0].finish_date
                else:
                    obj.last_modification_timestamp = archive_steps[0].start_date
            obj.state = ArchiveState.NONE
            for step in archive_steps:
                if step.status == Status.COMPLETED:
                    if step.name == Steps.CHECKSUM:
                        obj.state = ArchiveState.SIP
                        break
                    elif step.name == Steps.ARCHIVE:
                        obj.state = ArchiveState.AIP
                        break
        except Exception:
            obj.state = ArchiveState.NONE
        obj.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0010_alter_step_name'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE', reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='archive',
            name='last_completed_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_completed_step', to='oais.step'),
        ),
        migrations.AddField(
            model_name='archive',
            name='state',
            field=models.IntegerField(choices=[(1, 'NONE'), (2, 'SIP'), (3, 'AIP')], null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_RUN'), (2, 'IN_PROGRESS'), (3, 'FAILED'), (4, 'COMPLETED'), (5, 'WAITING_APPROVAL'), (6, 'REJECTED'), (7, 'WAITING')], default=1),
        ),
        migrations.AddField(
            model_name='archive',
            name='last_modification_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(save_archives, backwards),
        migrations.RunSQL(migrations.RunSQL.noop, reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
