# Generated by Django 4.2.1 on 2023-12-13 14:44

from django.db import migrations, models

from oais_platform.oais.models import ArchiveStatus, Status, Steps


def save_archives(apps, schema_editor):
    archives = apps.get_model("oais", "Archive")
    steps = apps.get_model("oais", "Step").objects.all()

    for obj in archives.objects.all():
        last_step = obj.last_step
        if last_step:
            if last_step.status == Status.COMPLETED:  # SIP was created
                if last_step.name == Steps.CHECKSUM:
                    obj.status = ArchiveStatus.SIP
                elif last_step.name == Steps.ARCHIVE:
                    obj.status = ArchiveStatus.AIP
                else:
                    obj.status = ArchiveStatus.COMPLETED
            else:
                obj.status = ArchiveStatus(last_step.status)
        else:
            try:
                last_step = steps.filter(archive=obj.id).order_by("-start_date")[0]  # If there was a step but it was not completed
                obj.status = ArchiveStatus(last_step.status)
            except Exception:
                obj.status = None
        
        obj.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0010_alter_step_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_RUN'), (2, 'IN_PROGRESS'), (3, 'FAILED'), (4, 'COMPLETED'), (5, 'WAITING_APPROVAL'), (6, 'REJECTED'), (7, 'WAITING'), (8, 'SIP'), (9, 'AIP')], null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_RUN'), (2, 'IN_PROGRESS'), (3, 'FAILED'), (4, 'COMPLETED'), (5, 'WAITING_APPROVAL'), (6, 'REJECTED'), (7, 'WAITING')], default=1),
        ),
        migrations.RunPython(save_archives, backwards),
    ]
