# Generated by Django 4.2.1 on 2024-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0011_alter_archive_state_add_last_completed_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cds_rdm_api_key',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='cds_rdm_sandbox_api_key',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
