# Generated by Django 5.0.6 on 2024-06-21 14:55

import django.db.models.deletion
import django.utils.timezone
import oais_platform.oais.models
from django.conf import settings
from django.db import migrations, models


def add_sources(apps, schema_editor):
    Source = apps.get_model("oais", "Source")
    Source.objects.create(name="cds", longname="CERN Document Server", api_url="https://cds.cern.ch", classname="CDS", 
                          how_to_get_key="From your browser, login to CDS, open your browser's developer tools (CTRL+SHIFT+I), go to the \"Storage\" tab and under cookies copy the value of the \"INVENIOSESSION\" cookie.")
    Source.objects.create(name="cds-test", longname="CERN Document Server TEST", api_url="https://cds-test.cern.ch", classname="CDS", enabled=False,
                          how_to_get_key="From your browser, login to CDS Test, open your browser's developer tools (CTRL+SHIFT+I), go to the \"Storage\" tab and under cookies copy the value of the \"INVENIOSESSION\" cookie.")
    Source.objects.create(name="zenodo", longname="Zenodo", api_url="https://zenodo.org/api", classname="Invenio", has_restricted_records=False)
    Source.objects.create(name="cds-rdm", longname="New CERN Document Repository", api_url="https://new-cds.cern.ch/api", classname="Invenio",
                          how_to_get_key="From your browser, login to the CDS-RDM instance, go to \"Applications\" then \"Personal access tokens\". Create new token, name can be anything. Note down the token and paste it here.")
    Source.objects.create(name="cds-rdm-sandbox", longname="New CERN Document Repository SANDBOX", api_url="https://sandbox-cds-rdm.web.cern.ch/api", classname="Invenio",
                          how_to_get_key="From your browser, login to the CDS-RDM instance, go to \"Applications\" then \"Personal access tokens\". Create new token, name can be anything. Note down the token and paste it here.")
    Source.objects.create(name="inveniordm", longname="InvenioRDM SANDBOX", api_url="https://inveniordm.web.cern.ch/api", classname="Invenio", enabled=False, has_restricted_records=False)
    Source.objects.create(name="cod", longname="CERN OpenData Portal", api_url="https://opendata.cern.ch/api", classname="Invenio", enabled=False, has_restricted_records=False)
    Source.objects.create(name="indico", longname="CERN Indico", api_url="https://indico.cern.ch", classname="Indico",
                          how_to_get_key="From your browser, login to the Indico instance, go to \"Preferences\" and then \"API Token\". Create new token, name can be anything. Select (at least) Everything (all methods) and Classic API (read only) as scopes. Note down the token and paste it here.")
    Source.objects.create(name="codimd", longname="CERN CodiMD", api_url="https://codimd.web.cern.ch", classname="CodiMD", has_public_records=False,
                          how_to_get_key="From your browser, login to the CodiMD instance and after the redirect to the main page open your browser's developer tools (CTRL+SHIFT+I), go to the \"Storage\" tab and under cookies copy the value of the connect.sid cookie. The Record ID for CodiMD document is the part of the url that follows the main domain address (e.g. in https://codimd.web.cern.ch/KabpdG3TTHKOsig2lq8tnw# the recid is KabpdG3TTHKOsig2lq8tnw).")


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0012_resource_resource_source_recid_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('longname', models.CharField(max_length=100, unique=True)),
                ('api_url', models.CharField(max_length=250, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('classname', models.CharField(choices=oais_platform.oais.models.get_source_classnames)),
                ('has_restricted_records', models.BooleanField(default=True)),
                ('has_public_records', models.BooleanField(default=True)),
                ('how_to_get_key', models.TextField(max_length=500, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='codimd_api_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='indico_api_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sso_comp_token',
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_key', models.TextField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oais.source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(fields=('user', 'source'), name='unique_user_source'),
        ),
        migrations.RunPython(add_sources, backwards),
    ]
