# Generated by Django 5.0.6 on 2024-09-11 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0013_source_remove_profile_codimd_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='next_steps',
        ),
        migrations.AddField(
            model_name='archive',
            name='pipeline_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='step',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.IntegerField(choices=[(1, 'Sip Upload'), (2, 'Harvest'), (3, 'Validation'), (4, 'Checksum'), (5, 'Archive'), (6, 'Edit Manifest'), (7, 'Invenio Rdm Push'), (8, 'Announce'), (9, 'Push Sip To Cta'), (10, 'Extract Title')]),
        ),
        migrations.AlterField(
            model_name='step',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
