# Generated by Django 5.0.6 on 2024-07-02 13:59

from django.db import migrations, models

from oais_platform.oais.models import ArchiveState


def update_archive_next_steps(apps, schema_editor):
    archives = apps.get_model("oais", "Archive")

    for obj in archives.objects.all():
        if (not obj.title or obj.title == "" or obj.title == f"{obj.source} - {obj.recid}") and obj.state != ArchiveState.NONE :
            if not obj.next_steps:
                obj.next_steps = [10]
            else:
                obj.next_steps.append(10)

        obj.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0013_source_remove_profile_codimd_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.IntegerField(choices=[(1, 'Sip Upload'), (2, 'Harvest'), (3, 'Validation'), (4, 'Checksum'), (5, 'Archive'), (6, 'Edit Manifest'), (7, 'Invenio Rdm Push'), (8, 'Announce'), (9, 'Push Sip To Cta'), (10, 'Extract Title')]),
        ),
        migrations.RunPython(update_archive_next_steps, backwards),
    ]
