# Generated by Django 5.0.6 on 2024-09-20 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0014_alter_step_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='next_steps',
        ),
        migrations.AddField(
            model_name='archive',
            name='pipeline_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='step',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='step',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
