# Generated by Django 5.0.6 on 2024-08-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0014_alter_step_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='pipeline_steps',
            field=models.JSONField(default=list, max_length=50),
        ),
    ]
