# Generated by Django 5.0.6 on 2024-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0015_archive_pipeline_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='pipeline_steps',
            field=models.JSONField(default=list),
        ),
    ]
