# Generated by Django 5.0.6 on 2024-11-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0015_remove_archive_next_steps_archive_pipeline_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.IntegerField(choices=[(1, 'Sip Upload'), (2, 'Harvest'), (3, 'Validation'), (4, 'Checksum'), (5, 'Archive'), (6, 'Edit Manifest'), (7, 'Invenio Rdm Push'), (8, 'Announce'), (9, 'Push To Cta'), (10, 'Extract Title')]),
        ),
    ]
