# Generated by Django 5.0.6 on 2024-11-13 13:16

from django.db import migrations, models
import json

from oais_platform.oais.models import Status, Steps


def add_archive_path_to_aip(apps, schema_editor):
    archives = apps.get_model("oais", "Archive")

    for obj in archives.objects.all():
        try:
            aip_step = (
                obj.steps.filter(name=Steps.ARCHIVE, status=Status.COMPLETED)
                .order_by("-start_date")
                .first()
            )
            aip_step_output = json.loads(aip_step.output_data)
            obj.path_to_aip = aip_step_output["artifact"]["artifact_path"]
            obj.save()
        except Exception:
            obj.path_to_aip = None


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0015_remove_archive_next_steps_archive_pipeline_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='path_to_aip',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.IntegerField(choices=[(1, 'Sip Upload'), (2, 'Harvest'), (3, 'Validation'), (4, 'Checksum'), (5, 'Archive'), (6, 'Edit Manifest'), (7, 'Invenio Rdm Push'), (8, 'Announce'), (9, 'Push To Cta'), (10, 'Extract Title')]),
        ),
        migrations.RunPython(add_archive_path_to_aip, backwards),
    ]
