# Generated by Django 5.0.6 on 2024-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0016_archive_path_to_aip_alter_step_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='notification_endpoint',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.IntegerField(choices=[(1, 'Sip Upload'), (2, 'Harvest'), (3, 'Validation'), (4, 'Checksum'), (5, 'Archive'), (6, 'Edit Manifest'), (7, 'Invenio Rdm Push'), (8, 'Announce'), (9, 'Push To Cta'), (10, 'Extract Title'), (11, 'Notify Source')]),
        ),
    ]
