# Generated by Django 5.0.6 on 2025-01-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0017_source_notification_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='last_completed_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_completed_step', to='oais.step'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='last_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_step', to='oais.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='oais.archive'),
        ),
        migrations.AlterField(
            model_name='step',
            name='input_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step', to='oais.step'),
        ),
    ]
