# Generated by Django 5.0.6 on 2025-02-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0018_alter_archive_last_completed_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cern_roles',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
