# Generated by Django 5.0.6 on 2025-02-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_approver_requester(apps, schema_editor):
    archives = apps.get_model("oais", "Archive")

    for obj in archives.objects.all():
        obj.approver = obj.requester
        obj.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0019_remove_profile_cern_roles_profile_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-id'], 'permissions': (('can_approve_all', 'Can approve any record and start the pipeline'), ('view_archive_all', 'Can view all archives'), ('can_edit_all', 'Can edit all archives'))},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_execute_step', 'Can execute steps')]},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={},
        ),
        migrations.RenameField(
            model_name="archive",
            old_name="creator",
            new_name="requester",
        ),
        migrations.AlterField(
            model_name='archive',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archive',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_archives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_approver_requester, backwards),
    ]
