# Generated by Django 5.0.6 on 2025-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0020_alter_archive_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
