# Generated by Django 5.0.6 on 2025-08-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0021_alter_archive_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='original_file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archive',
            name='sip_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
