# Generated by Django 5.0.6 on 2025-09-19 07:35

import django.contrib.postgres.fields
import django.db.models.deletion
import oais_platform.oais.models
from django.conf import settings
from django.db import migrations, models
from oais_platform.oais.models import StepName


def add_step_types(apps, schema_editor):
    StepType = apps.get_model("oais", "StepType")

    harvest = StepType.objects.create(name=StepName.HARVEST, label="Harvest", description="Harvest from upstream source", task_name="harvest", has_sip=True, automatic_next_step=True)
    validate = StepType.objects.create(name=StepName.VALIDATION, label="Validation", description="Validate SIP structure and contents", task_name="validate", automatic_next_step=True)
    checksum = StepType.objects.create(name=StepName.CHECKSUM, label="Checksum", description="Verify checksums", task_name="checksum")
    archive = StepType.objects.create(name=StepName.ARCHIVE, label="Archive", description="Create the Preservation Bag", task_name="archivematica", has_aip=True)
    cta = StepType.objects.create(name=StepName.PUSH_TO_CTA, label="Push to CTA", description="Copy Preservation Bag to Long Term Storage", task_name="push_to_cta")
    registry = StepType.objects.create(name=StepName.INVENIO_RDM_PUSH, label="Push to Registry", description="Register bag in central registry", task_name="process_invenio")
    announce = StepType.objects.create(name=StepName.ANNOUNCE, label="Announce", description="Process SIP from CERN cloud", task_name="announce", has_sip=True, automatic_next_step=True)
    extract = StepType.objects.create(name=StepName.EXTRACT_TITLE, label="Extract Title", description="Extract title from SIP metadata", task_name="extract_title")
    notify = StepType.objects.create(name=StepName.NOTIFY_SOURCE, label="Notify Source", description="Notify upstream source about the preservation", task_name="notify_source")
    upload = StepType.objects.create(name=StepName.SIP_UPLOAD, label="SIP Upload", description="Upload SIP", has_sip=True, automatic_next_step=True)
    edit = StepType.objects.create(name=StepName.EDIT_MANIFEST, label="Edit Manifest", description="Edit manifest file")

    harvest.next_steps.set([validate])
    validate.next_steps.set([checksum])
    upload.next_steps.set([validate])
    announce.next_steps.set([validate])
    checksum.next_steps.set([archive, registry])
    archive.next_steps.set([cta, registry, archive, notify])
    cta.next_steps.set([cta, registry, archive])
    registry.next_steps.set([cta, registry, archive])
    extract.next_steps.set([registry, archive])
    notify.next_steps.set([registry, archive, cta])
    edit.next_steps.set([registry, archive])

    harvest.save()
    validate.save()
    checksum.save()
    archive.save()
    cta.save()
    registry.save()
    announce.save()
    extract.save()
    notify.save()
    upload.save()
    edit.save()

    Step = apps.get_model("oais", "Step")
    steps = Step.objects.all()
    for step in steps:
        if step.name:
            match step.name:
                case 1:
                    step_type = upload
                case 2:
                    step_type = harvest
                case 3:
                    step_type = validate
                case 4:
                    step_type = checksum
                case 5:
                    step_type = archive
                case 6:
                    step_type = edit
                case 7:
                    step_type = registry
                case 8:
                    step_type = announce
                case 9:
                    step_type = cta
                case 10:
                    step_type = extract
                case 11:
                    step_type = notify
            if step_type:
                step.step_type = step_type
                step.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('oais', '0022_archive_original_file_size_archive_sip_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'IN_PROGRESS'), (3, 'COMPLETED'), (4, 'BLOCKED'), (5, 'PARTIALLY_COMPLETED')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('records', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['batch_number'],
            },
        ),
        migrations.AddField(
            model_name='step',
            name='initiated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='step',
            name='initiated_by_harvest_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='oais.harvestbatch'),
        ),
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SIP_UPLOAD', 'Sip Upload'), ('HARVEST', 'Harvest'), ('VALIDATION', 'Validation'), ('CHECKSUM', 'Checksum'), ('ARCHIVE', 'Archive'), ('EDIT_MANIFEST', 'Edit Manifest'), ('INVENIO_RDM_PUSH', 'Invenio Rdm Push'), ('ANNOUNCE', 'Announce'), ('PUSH_TO_CTA', 'Push To Cta'), ('EXTRACT_TITLE', 'Extract Title'), ('NOTIFY_SOURCE', 'Notify Source')]), blank=True, default=list, size=None)),
                ('query_start_time', models.DateTimeField(default=None, null=True)),
                ('query_end_time', models.DateTimeField(default=None, null=True)),
                ('condition_unmodified_for_days', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvest_runs', to='oais.collection')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_runs', to='oais.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='harvestbatch',
            name='harvest_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='oais.harvestrun'),
        ),
        migrations.CreateModel(
            name='ScheduledHarvest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('pipeline', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SIP_UPLOAD', 'Sip Upload'), ('HARVEST', 'Harvest'), ('VALIDATION', 'Validation'), ('CHECKSUM', 'Checksum'), ('ARCHIVE', 'Archive'), ('EDIT_MANIFEST', 'Edit Manifest'), ('INVENIO_RDM_PUSH', 'Invenio Rdm Push'), ('ANNOUNCE', 'Announce'), ('PUSH_TO_CTA', 'Push To Cta'), ('EXTRACT_TITLE', 'Extract Title'), ('NOTIFY_SOURCE', 'Notify Source')]), blank=True, default=list, size=None)),
                ('condition_unmodified_for_days', models.PositiveIntegerField(default=0)),
                ('scheduling_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_harvests', to='oais.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='harvestrun',
            name='scheduled_harvest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_runs', to='oais.scheduledharvest'),
        ),
        migrations.CreateModel(
            name='StepType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('SIP_UPLOAD', 'Sip Upload'), ('HARVEST', 'Harvest'), ('VALIDATION', 'Validation'), ('CHECKSUM', 'Checksum'), ('ARCHIVE', 'Archive'), ('EDIT_MANIFEST', 'Edit Manifest'), ('INVENIO_RDM_PUSH', 'Invenio Rdm Push'), ('ANNOUNCE', 'Announce'), ('PUSH_TO_CTA', 'Push To Cta'), ('EXTRACT_TITLE', 'Extract Title'), ('NOTIFY_SOURCE', 'Notify Source')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(default=None, max_length=250, null=True)),
                ('task_name', models.CharField(choices=oais_platform.oais.models.get_task_names, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_count', models.IntegerField(default=0)),
                ('failed_blocking_limit', models.IntegerField(default=None, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('has_sip', models.BooleanField(default=False)),
                ('has_aip', models.BooleanField(default=False)),
                ('automatic_next_step', models.BooleanField(default=False)),
                ('next_steps', models.ManyToManyField(blank=True, help_text='Steps that can follow this step', related_name='preceding_steps', to='oais.steptype')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='step_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='oais.steptype'),
        ),
        migrations.AlterUniqueTogether(
            name='harvestbatch',
            unique_together={('harvest_run', 'batch_number')},
        ),
        migrations.RunPython(add_step_types, backwards),
        migrations.RemoveField(
            model_name='step',
            name='name',
        ),
        migrations.AlterField(
            model_name='harvestbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('PARTIALLY_FAILED', 'Partially Failed')], default='PENDING'),
        ),
    ]
