# Generated by Django 5.0.6 on 2025-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0023_harvestbatch_remove_step_name_step_initiated_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrun',
            name='batch_delay_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='harvestrun',
            name='batch_size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scheduledharvest',
            name='batch_delay_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='scheduledharvest',
            name='batch_size',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
