# Generated by Django 5.0.6 on 2025-09-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0023_harvestbatch_remove_step_name_step_initiated_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='name',
        ),
    ]
