# Generated by Django 5.0.6 on 2025-09-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0024_remove_step_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestbatch',
            name='status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'IN_PROGRESS'), (3, 'COMPLETED'), (4, 'BLOCKED'), (5, 'PARTIALLY_FAILED')], default=1),
        ),
    ]
