# Generated by Django 5.0.6 on 2025-10-13 08:44

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def add_system_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('oais', 'Profile')

    # Try to find existing system user, fallback to admin or system_user
    system_user = None
    for username in ['oais', 'admin', "system_user"]:
        try:
            system_user = User.objects.get(username=username)
            break
        except User.DoesNotExist:
            continue

    # If no existing user found, create the system user
    if not system_user:
        system_user = User.objects.create_user(
            username='system_user',
            email='system@example.com',
            password=make_password(None),  # password is set unusable
        )

    # Get or create the profile
    try:
        profile = Profile.objects.get(user=system_user)
        profile.system = True
        profile.save()
    except Profile.DoesNotExist:
        Profile.objects.create(user=system_user, system=True)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0024_harvestrun_batch_delay_minutes_harvestrun_batch_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestrun',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduledharvest',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(condition=models.Q(('system', True)), fields=('system',), name='unique_system_user'),
        ),
        migrations.RunPython(add_system_user, backwards),
    ]
