# Generated by Django 5.0.6 on 2025-10-21 11:47

import django.contrib.postgres.fields
from django.db import migrations, models

from oais_platform.oais.models import StepName


def add_upload_steptype(apps, schema_editor):
    StepType = apps.get_model("oais", "StepType")

    if not StepType.objects.filter(name="FILE_UPLOAD").exists():
        StepType.objects.create(
            name="FILE_UPLOAD",
            label="Local file upload",
            description="Uploading local files and creating SIP",
            task_name="upload",
            has_sip=True,
            automatic_next_step=StepType.objects.get(name=StepName.VALIDATION),
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("oais", "0025_remove_harvestrun_user_remove_scheduledharvest_user_and_more"),
    ]

    operations = [
        migrations.RunPython(add_upload_steptype, backwards),
        migrations.AlterField(
            model_name="harvestrun",
            name="pipeline",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("FILE_UPLOAD", "File Upload"),
                        ("SIP_UPLOAD", "Sip Upload"),
                        ("HARVEST", "Harvest"),
                        ("VALIDATION", "Validation"),
                        ("CHECKSUM", "Checksum"),
                        ("ARCHIVE", "Archive"),
                        ("EDIT_MANIFEST", "Edit Manifest"),
                        ("INVENIO_RDM_PUSH", "Invenio Rdm Push"),
                        ("ANNOUNCE", "Announce"),
                        ("PUSH_TO_CTA", "Push To Cta"),
                        ("EXTRACT_TITLE", "Extract Title"),
                        ("NOTIFY_SOURCE", "Notify Source"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledharvest",
            name="pipeline",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("FILE_UPLOAD", "File Upload"),
                        ("SIP_UPLOAD", "Sip Upload"),
                        ("HARVEST", "Harvest"),
                        ("VALIDATION", "Validation"),
                        ("CHECKSUM", "Checksum"),
                        ("ARCHIVE", "Archive"),
                        ("EDIT_MANIFEST", "Edit Manifest"),
                        ("INVENIO_RDM_PUSH", "Invenio Rdm Push"),
                        ("ANNOUNCE", "Announce"),
                        ("PUSH_TO_CTA", "Push To Cta"),
                        ("EXTRACT_TITLE", "Extract Title"),
                        ("NOTIFY_SOURCE", "Notify Source"),
                    ]
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="steptype",
            name="name",
            field=models.CharField(
                choices=[
                    ("FILE_UPLOAD", "File Upload"),
                    ("SIP_UPLOAD", "Sip Upload"),
                    ("HARVEST", "Harvest"),
                    ("VALIDATION", "Validation"),
                    ("CHECKSUM", "Checksum"),
                    ("ARCHIVE", "Archive"),
                    ("EDIT_MANIFEST", "Edit Manifest"),
                    ("INVENIO_RDM_PUSH", "Invenio Rdm Push"),
                    ("ANNOUNCE", "Announce"),
                    ("PUSH_TO_CTA", "Push To Cta"),
                    ("EXTRACT_TITLE", "Extract Title"),
                    ("NOTIFY_SOURCE", "Notify Source"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="UploadJob",
        ),
    ]
