# Generated by Django 5.0.6 on 2025-10-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0026_alter_harvestrun_pipeline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_execute_step', 'Can execute steps'), ('can_upload_file', 'Can upload files')]},
        ),
    ]
