# Generated by Django 5.0.6 on 2025-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0028_personalaccesstoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvestrun',
            old_name='condition_unmodified_for_days',
            new_name='grace_period_days',
        ),
        migrations.RenameField(
            model_name='scheduledharvest',
            old_name='condition_unmodified_for_days',
            new_name='grace_period_days',
        ),
        migrations.AddField(
            model_name='archive',
            name='version_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='harvestbatch',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='harvestrun',
            name='filter_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default='updated'),
        ),
        migrations.AddField(
            model_name='scheduledharvest',
            name='filter_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], default='updated'),
        ),
    ]
