# Generated by Django 5.0.6 on 2025-12-05 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0028_personalaccesstoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_reason', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=0)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('archives', models.ManyToManyField(related_name='requests', to='oais.archive')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'permissions': (('can_approve_requests', 'Can approve or reject archive requests'),),
            },
        ),
    ]
