# Generated by Django 5.0.6 on 2025-12-04 14:49

from django.db import migrations, models

from oais_platform.oais.models import StepName


def set_default_values_for_steptype(apps, schema_editor):
    StepType = apps.get_model('oais', 'StepType')
    archive_step = StepType.objects.get(name=StepName.ARCHIVE)
    archive_step.concurrency_limit = 100
    archive_step.size_limit_bytes = 50 * 1024**3  # 50 GB
    archive_step.save()

    harvest_step = StepType.objects.get(name=StepName.HARVEST)
    harvest_step.size_limit_bytes = 50 * 1024**3  # 50 GB
    harvest_step.save()

    cta_step = StepType.objects.get(name=StepName.PUSH_TO_CTA)
    cta_step.concurrency_limit = 200
    cta_step.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0029_rename_condition_unmodified_for_days_harvestrun_grace_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptype',
            name='concurrency_limit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='steptype',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='steptype',
            name='current_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='steptype',
            name='size_limit_bytes',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.RunPython(set_default_values_for_steptype, backwards),
    ]
