# Generated by Django 5.0.6 on 2025-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0030_steptype_concurrency_limit_steptype_current_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_RUN'), (2, 'IN_PROGRESS'), (3, 'FAILED'), (4, 'COMPLETED'), (5, 'WAITING_APPROVAL'), (6, 'REJECTED'), (7, 'WAITING'), (8, 'COMPLETED_WITH_WARNINGS')], default=1),
        ),
    ]
