# Generated by Django 5.0.6 on 2025-12-04 14:49

from django.db import migrations, models

from oais_platform.oais.models import StepName



def remove_checksum_automatic_next_step(apps, schema_editor):
    StepType = apps.get_model("oais", "StepType")

    try:
        validation = StepType.objects.get(name="VALIDATION")
    except StepType.DoesNotExist:
        return

    # Remove automatic next step
    validation.automatic_next_step = None
    validation.save(update_fields=["automatic_next_step"])

    StepType.objects.filter(name="CHECKSUM").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0031_alter_step_status'),
    ]
    operations = [
        migrations.RunPython(remove_checksum_automatic_next_step),
    ]

