# Generated by Django 5.0.6 on 2026-01-15 10:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oais", "0032_remove_checksum_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="path_to_sip",
            field=models.CharField(max_length=250),
        )
    ]
