# Generated by Django 5.0.6 on 2026-01-16 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0032_remove_checksum_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrun',
            name='pipeline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('SIP_UPLOAD', 'Sip Upload'), ('HARVEST', 'Harvest'), ('VALIDATION', 'Validation'), ('ARCHIVE', 'Archive'), ('EDIT_MANIFEST', 'Edit Manifest'), ('INVENIO_RDM_PUSH', 'Invenio Rdm Push'), ('ANNOUNCE', 'Announce'), ('PUSH_TO_CTA', 'Push To Cta'), ('EXTRACT_TITLE', 'Extract Title'), ('NOTIFY_SOURCE', 'Notify Source')]), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='scheduledharvest',
            name='pipeline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('SIP_UPLOAD', 'Sip Upload'), ('HARVEST', 'Harvest'), ('VALIDATION', 'Validation'), ('ARCHIVE', 'Archive'), ('EDIT_MANIFEST', 'Edit Manifest'), ('INVENIO_RDM_PUSH', 'Invenio Rdm Push'), ('ANNOUNCE', 'Announce'), ('PUSH_TO_CTA', 'Push To Cta'), ('EXTRACT_TITLE', 'Extract Title'), ('NOTIFY_SOURCE', 'Notify Source')]), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='steptype',
            name='name',
            field=models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('SIP_UPLOAD', 'Sip Upload'), ('HARVEST', 'Harvest'), ('VALIDATION', 'Validation'), ('ARCHIVE', 'Archive'), ('EDIT_MANIFEST', 'Edit Manifest'), ('INVENIO_RDM_PUSH', 'Invenio Rdm Push'), ('ANNOUNCE', 'Announce'), ('PUSH_TO_CTA', 'Push To Cta'), ('EXTRACT_TITLE', 'Extract Title'), ('NOTIFY_SOURCE', 'Notify Source')], max_length=50, unique=True),
        ),
    ]
