# Generated by Django 5.0.6 on 2026-03-13 14:00

import json

from django.db import migrations, models


def migrate_text_to_json(apps, schema_editor):
    Step = apps.get_model("oais", "Step")

    for step in Step.objects.all():
        step.input_data_json = (
            try_parse_json(step.input_data) if step.input_data else {}
        )
        step.output_data_json = (
            try_parse_json(step.output_data) if step.output_data else {}
        )

        step.save(update_fields=["input_data_json", "output_data_json"])


def try_parse_json(value):
    if not value:
        return {}
    try:
        return json.loads(value)
    except (json.JSONDecodeError, TypeError):
        return {"data": value}


class Migration(migrations.Migration):

    dependencies = [
        ("oais", "0036_alter_step_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="input_data_json",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="step",
            name="output_data_json",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.RunPython(migrate_text_to_json),
    ]
