# Generated by Django 5.0.6 on 2026-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oais", "0036_alter_step_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="input_data_json",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="step",
            name="output_data_json",
            field=models.JSONField(default=None, null=True),
        ),
    ]
