# Generated by Django 5.0.6 on 2026-04-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0038_step_failure_type_alter_step_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steptype',
            name='current_count',
        ),
        migrations.RemoveField(
            model_name='steptype',
            name='current_size_bytes',
        ),
        migrations.AlterField(
            model_name='step',
            name='failure_type',
            field=models.CharField(choices=[('TIMEOUT', 'Timeout'), ('CONNECTION_ERROR', 'Connection Error'), ('FILE_ALREADY_EXISTS', 'File Already Exists'), ('MISSING_INPUT_DATA', 'Missing Input Data'), ('MISSING_OUTPUT_DATA', 'Missing Output Data'), ('USER_INPUT_REQUIRED', 'User Input Required'), ('SIZE_EXCEEDED', 'Size Exceeded'), ('AGGR_SIZE_EXCEEDED', 'Aggr Size Exceeded'), ('PACKAGE_NOT_FOUND', 'Package Not Found'), ('PATH_NOT_FOUND', 'Path Not Found'), ('INVALID_SCHEMA', 'Invalid Schema'), ('CHECKSUM_MISMATCH', 'Checksum Mismatch'), ('STEP_DISABLED', 'Step Disabled'), ('STORAGE_FULL', 'Storage Full'), ('HTTP_400', 'Http 400'), ('HTTP_401', 'Http 401'), ('HTTP_403', 'Http 403'), ('HTTP_404', 'Http 404'), ('HTTP_429', 'Http 429'), ('HTTP_500', 'Http 500'), ('HTTP_502', 'Http 502'), ('HTTP_REDIRECT', 'Http Redirect'), ('HTTP_OTHER', 'Http Other'), ('OTHER', 'Other')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_RUN'), (2, 'IN_PROGRESS'), (3, 'FAILED'), (4, 'COMPLETED'), (5, 'WAITING_APPROVAL'), (6, 'REJECTED'), (7, 'WAITING'), (8, 'COMPLETED_WITH_WARNINGS'), (10, 'OUTDATED'), (11, 'SUBMITTED')], default=1),
        ),
    ]
