# Generated by Django 5.0.6 on 2026-05-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0039_remove_steptype_current_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='failure_type',
            field=models.CharField(choices=[('TIMEOUT', 'Timeout'), ('CONNECTION_ERROR', 'Connection Error'), ('FILE_ALREADY_EXISTS', 'File Already Exists'), ('MISSING_INPUT_DATA', 'Missing Input Data'), ('MISSING_OUTPUT_DATA', 'Missing Output Data'), ('USER_INPUT_REQUIRED', 'User Input Required'), ('SIZE_EXCEEDED', 'Size Exceeded'), ('AGGR_SIZE_EXCEEDED', 'Aggr Size Exceeded'), ('PACKAGE_NOT_FOUND', 'Package Not Found'), ('PATH_NOT_FOUND', 'Path Not Found'), ('INVALID_SCHEMA', 'Invalid Schema'), ('CHECKSUM_MISMATCH', 'Checksum Mismatch'), ('STEP_DISABLED', 'Step Disabled'), ('STORAGE_FULL', 'Storage Full'), ('VIRUS_FLAGGED', 'Virus Flagged'), ('EXTRACTION_FAILED', 'Extraction Failed'), ('NORMALIZATION_FAILED', 'Normalization Failed'), ('AM_JOB_FAILED_OTHER', 'Am Job Failed Other'), ('HTTP_400', 'Http 400'), ('HTTP_401', 'Http 401'), ('HTTP_403', 'Http 403'), ('HTTP_404', 'Http 404'), ('HTTP_429', 'Http 429'), ('HTTP_500', 'Http 500'), ('HTTP_502', 'Http 502'), ('HTTP_REDIRECT', 'Http Redirect'), ('HTTP_OTHER', 'Http Other'), ('OTHER', 'Other')], default=None, max_length=50, null=True),
        ),
    ]
