# Generated by Django 5.0.6 on 2026-05-11 09:37

from django.db import migrations, models


def add_archives_to_harvest_batch(apps, schema_editor):
    HarvestBatch = apps.get_model("oais", "HarvestBatch")
    Archive = apps.get_model("oais", "Archive")
    for batch in HarvestBatch.objects.all():
        archives = Archive.objects.filter(steps__initiated_by_harvest_batch=batch).distinct()
        batch.archives.set(archives)


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0040_alter_step_failure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestbatch',
            name='archives',
            field=models.ManyToManyField(blank=True, related_name='harvest_batches', to='oais.archive'),
        ),
        migrations.RunPython(add_archives_to_harvest_batch),
    ]
