# Generated by Django 5.0.6 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oais", "0041_harvestbatch_archives"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="archivematica_instance",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
