# Generated by Django 5.0.6 on 2026-06-12 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0041_harvestbatch_archives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['archive', 'step_type', '-start_date', '-create_date'], name='oais_step_archive_69171b_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['status', 'step_type'], name='oais_step_status_f8c3a0_idx'),
        ),
    ]
