# Generated by Django 5.0.6 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0042_step_oais_step_archive_69171b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='archivematica_instance',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
