# Generated by Django 5.0.6 on 2026-07-28 11:40

from django.db import migrations


def add_cds_videos(apps, schema_editor):
    Source = apps.get_model("oais", "Source")
    Source.objects.create(name="cds-videos", longname="CDS Videos", api_url="https://videos.cern.ch/api", classname="Invenio",
                              how_to_get_key="From your browser, login to the CDS-Videos instance, go to \"Applications\" then \"Personal access tokens\". Create new token, name can be anything. Note down the token and paste it here.")
    Source.objects.create(name="sandbox-videos", longname="Sandbox CDS Videos", api_url="https://sandbox-videos.web.cern.ch/api", classname="Invenio",
                                  how_to_get_key="From your browser, login to the CDS-Videos instance, go to \"Applications\" then \"Personal access tokens\". Create new token, name can be anything. Note down the token and paste it here.")

def remove_cds_videos(apps, schema_editor):
    Source = apps.get_model("oais", "Source")
    Source.objects.filter(
        name__in=["cds-videos", "sandbox-videos"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0042_step_oais_step_archive_69171b_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_cds_videos,
            reverse_code=remove_cds_videos,
        ),
    ]
