# Generated by Django 5.0.6 on 2026-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0043_auto_20260728_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrun',
            name='extra_query',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scheduledharvest',
            name='extra_query',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
