# Generated by Django 5.0.6 on 2026-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0043_archive_archivematica_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.IntegerField(choices=[(1, 'NOT_RUN'), (2, 'IN_PROGRESS'), (3, 'FAILED'), (4, 'COMPLETED'), (5, 'WAITING_APPROVAL'), (6, 'REJECTED'), (7, 'WAITING'), (8, 'COMPLETED_WITH_WARNINGS'), (10, 'OUTDATED'), (11, 'SUBMITTED'), (12, 'ASSIGNED')], default=1),
        ),
    ]
