# Generated by Django 5.0.6 on 2026-08-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0043_auto_20260728_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledharvest',
            name='record_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
