# Generated by Django 5.0.6 on 2026-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0044_scheduledharvest_record_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrun',
            name='extra_query',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scheduledharvest',
            name='extra_query',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
