# Generated by Django 5.0.6 on 2026-07-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oais", "0045_harvestrun_extra_query_scheduledharvest_extra_query"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivematicaInstance",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(max_length=250)),
                ("username", models.CharField(max_length=150)),
                ("_api_key", models.TextField(db_column="api_key")),
                ("storage_service_url", models.URLField(max_length=250)),
                (
                    "storage_service_username",
                    models.CharField(max_length=150),
                ),
                (
                    "_storage_service_api_key",
                    models.TextField(db_column="storage_service_api_key"),
                ),
                ("sip_upstream_basepath", models.CharField(max_length=250)),
                ("aip_upstream_basepath", models.CharField(max_length=250)),
                (
                    "transfer_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("retry_limit", models.PositiveIntegerField(default=2)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="archive",
            name="archivematica_instance",
            field=models.ForeignKey(
                db_column="archivematica_instance",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archives",
                to="oais.archivematicainstance",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "NOT_RUN"),
                    (2, "IN_PROGRESS"),
                    (3, "FAILED"),
                    (4, "COMPLETED"),
                    (5, "WAITING_APPROVAL"),
                    (6, "REJECTED"),
                    (7, "WAITING"),
                    (8, "COMPLETED_WITH_WARNINGS"),
                    (10, "OUTDATED"),
                    (11, "SUBMITTED"),
                    (12, "ASSIGNED"),
                ],
                default=1,
            ),
        ),
    ]
