# Generated by Django 5.0.6 on 2026-09-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0046_archivematicainstance_archive_archivematica_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivematicainstance',
            name='version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='archivematicainstance',
            name='version_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
