# Generated by Django 5.0.6 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oais", "0046_archive_archivematica_instance_alter_step_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivematicaInstance",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("url", models.URLField(max_length=250)),
                ("username", models.CharField(max_length=150)),
                ("_api_key", models.TextField(db_column="api_key")),
                ("storage_service_url", models.URLField(max_length=250)),
                (
                    "storage_service_username",
                    models.CharField(max_length=150),
                ),
                (
                    "_storage_service_api_key",
                    models.TextField(db_column="storage_service_api_key"),
                ),
                ("sip_upstream_basepath", models.CharField(max_length=250)),
                ("aip_upstream_basepath", models.CharField(max_length=250)),
                (
                    "transfer_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("retry_limit", models.PositiveIntegerField(default=2)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="archive",
            name="archivematica_instance",
            field=models.ForeignKey(
                db_column="archivematica_instance",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archives",
                to="oais.archivematicainstance",
            ),
        ),
    ]
