# Generated by Django 5.0.6 on 2026-09-24 07:25

from django.db import migrations, models
from pathlib import Path

def fill_aip_size_for_existing_archives(apps, schema_editor):
    Archive = apps.get_model("oais", "Archive")
    for archive in Archive.objects.all():

        if not archive.path_to_aip:
            continue

        path = Path(archive.path_to_aip)

        if path.is_file():
            # AIPs are stored as a single compressed file (e.g. .7z),
            # so rglob("*") would silently return nothing here.
            size = path.stat().st_size
        elif path.is_dir():
            size = sum(
                file.stat().st_size for file in path.rglob("*") if file.is_file()
            )
        else:
            continue

        archive.aip_size = size
        archive.save(update_fields=["aip_size"])


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0047_archivematicainstance_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='aip_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(
            fill_aip_size_for_existing_archives,
            migrations.RunPython.noop,
        ),
    ]
