# Generated by Django 5.0.6 on 2026-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oais', '0047_archivematicainstance_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='aip_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
